[project]
name = "fastapi-test-app"
version = "1.0.0"
description = "A minimal FastAPI app for VPS deployment testing"
requires-python = ">=3.11"
dependencies = ["fastapi>=0.104.1", "uvicorn[standard]>=0.24.0"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
