name: Deploy FastAPI to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Build Docker image
      run: |
        docker build -t fastapi-test-app .
        docker save fastapi-test-app > fastapi-test-app.tar
    
    - name: Copy Docker image to VPS
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        source: "fastapi-test-app.tar"
        target: "/tmp/"
    
    - name: Deploy on VPS
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          # Load the Docker image
          docker load < /tmp/fastapi-test-app.tar
          
          # Stop and remove existing container if running
          docker stop fastapi-test-app || true
          docker rm fastapi-test-app || true
          
          # Remove old image to save space
          docker image prune -f
          
          # Run new container with environment variables
          docker run -d \
            --name fastapi-test-app \
            -p 80:8000 \
            -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            -e API_SECRET_KEY="${{ secrets.API_SECRET_KEY }}" \
            -e DEBUG_MODE="${{ secrets.DEBUG_MODE }}" \
            --restart unless-stopped \
            fastapi-test-app
          
          # Clean up the tar file
          rm /tmp/fastapi-test-app.tar
          
          # Show container status
          docker ps | grep fastapi-test-app